<a href="https://colab.research.google.com/github/Krishanu2206/Spam_Classifier/blob/main/Spam_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SPAM CLASSIFIER



##Getting the Dataset READY!!

In [1]:
import pandas as pd

In [7]:
messages = pd.read_csv('/content/spam.csv', encoding='latin-1')

In [12]:
messages.head(5)

labels                                           messages
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [35]:
type(messages)

pandas.core.frame.DataFrame

In [34]:
len(messages)

5572

In [9]:
messages.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)

In [11]:
#change the column names to labels and messages
messages.columns = ['labels', 'messages']

In [13]:
messages.columns

Index(['labels', 'messages'], dtype='object')

In [14]:
messages['labels'].value_counts()

labels
ham     4825
spam     747
Name: count, dtype: int64

In [116]:
messages['labels'].values

array(['ham', 'ham', 'spam', ..., 'ham', 'ham', 'ham'], dtype=object)

In [70]:
messages['messages'][0:10]

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
5    FreeMsg Hey there darling it's been 3 week's n...
6    Even my brother is not like to speak with me. ...
7    As per your request 'Melle Melle (Oru Minnamin...
8    WINNER!! As a valued network customer you have...
9    Had your mobile 11 months or more? U R entitle...
Name: messages, dtype: object

In [71]:
messages.iloc[0,1] ##getting a string as a result

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [23]:
messages.iloc[0:10,1].values

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       'U dun say so early hor... U c already then say...',
       "Nah I don't think he goes to usf, he lives around here though",
       "FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv",
       'Even my brother is not like to speak with me. They treat me like aids patent.',
       "As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune",
       'WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 0906170

In [22]:
type(messages.iloc[0:10,1].values)

numpy.ndarray

FINALLY! WE HAVE THE DATASET READY!!

##Cleaning the texts and text preprocessing

In [25]:
##installing dependencies
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [39]:
ps=PorterStemmer()
corpus=[]
for i in range(len(messages)):
  review=re.sub('[^a-zA-Z]', ' ', messages['messages'][i])
  review=review.lower()
  review=review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [41]:
corpus[0:10]

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free']

In [45]:
##Creating the Bag Od Words Model
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)
X=cv.fit_transform(corpus).toarray()

In [46]:
X.shape

(5572, 5000)

In [87]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [89]:
##use One-Hot Encoder to break spam and hams
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
## y = ohe.fit_transform(messages['labels'][:].values.reshape(-1,1)) ##you can also write like this
y=ohe.fit_transform(messages[['labels']])
y.columns=['ham', 'spam']

In [90]:
y.iloc[0:10]

ham  spam
0  1.0   0.0
1  1.0   0.0
2  0.0   1.0
3  1.0   0.0
4  1.0   0.0
5  0.0   1.0
6  1.0   0.0
7  1.0   0.0
8  0.0   1.0
9  0.0   1.0

In [93]:
##use Ordinal Encoder to break spam and hams
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
## y = ohe.fit_transform(messages['labels'][:].values.reshape(-1,1)) ##you can also write like this
y=oe.fit_transform(messages[['labels']])
y

array([[0.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [131]:
y=y.squeeze()

##Training and Testing

In [132]:
##train_test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8, random_state=42)

In [133]:
X_train.shape, y_train.shape

((4457, 5000), (4457,))

In [134]:
##Training Model using Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred = spam_detect_model.predict(X_test)

In [135]:
type(y_pred)

numpy.ndarray

In [140]:
y_pred, y_test

(array([0., 0., 1., ..., 0., 0., 1.]), array([0., 0., 1., ..., 0., 0., 1.]))

In [137]:
##checking the accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9775784753363229

In [138]:
len(y_test), len(y_pred)

(1115, 1115)

In [139]:
compare = pd.DataFrame({
    'actual' : y_test,
    'predicted' : y_pred
})
compare.head(10)

actual  predicted
0     0.0        0.0
1     0.0        0.0
2     1.0        1.0
3     0.0        0.0
4     1.0        1.0
5     0.0        0.0
6     0.0        0.0
7     0.0        0.0
8     0.0        0.0
9     0.0        0.0

##Checking with some random texts

In [99]:
text = "You’ve won!"
test_pred = spam_detect_model.predict(cv.transform([text]))
test_pred

array([0.])

WELL DONE!